# Makefile for Paladin_Dungeon

FLAGS=-Wall -Werror -Wextra
YELLOW=\x1b[33m
WHITE=\x1b[0m

#Paladin&Dungeon:
#	gcc $(FLAGS) main.c -o Paladin&Dungeon

Paladin_Dungeon:
	gcc main.c -o Paladin_Dungeon
	
clean:
	rm -rf *.o
	rm -rf Paladin_Dungeon
